projects:
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  app:
    schemaPath: src/schema_.graphql
    extensions:
      endpoints:
        default: https://lovebird-komunitas.herokuapp.com/